// Doc builders shared by generate.mjs and check.mjs. Kept pure so CI can build
// the same bytes twice and diff them instead of trusting anyone's memory.

const HEADER =
  "<!-- AUTO-GENERATED by scripts/sync/generate.mjs — run `npm run sync`. Do not edit by hand. -->";

function credentialLabel(channel) {
  return `\`${channel.header}\`<br/>${channel.plane}`;
}

export function buildApiDoc({ routes, workflows, consumerRefs, allowlist }) {
  const lines = [
    HEADER,
    "",
    "# Automation API surface",
    "",
    "Canonical inventory of everything under `/api/public`, generated straight",
    "from the route files. If an endpoint is not here it does not exist. If it is",
    "not in *Who calls what* either, nothing consumes it.",
    "",
    "## Endpoints",
    "",
    "| Endpoint | Methods | Credential | What it does |",
    "| --- | --- | --- | --- |",
  ];

  for (const route of routes) {
    lines.push(
      `| \`${route.path}\` | ${route.methods.join(", ")} | ${credentialLabel(route.channel)} | ${route.description} |`,
    );
  }

  lines.push("", "## Who calls what", "");

  const consumers = [];
  for (const wf of workflows) {
    if (wf.calls.length > 0) consumers.push([`${wf.name} (${wf.label})`, wf.calls]);
  }
  for (const [refPath, source] of [...consumerRefs.entries()].sort((a, b) =>
    a[0].localeCompare(b[0]),
  )) {
    // Wildcards from architecture.md cover many routes; list them once as-is.
    consumers.push([source, [refPath]]);
  }

  const seen = new Set();
  for (const [source, paths] of consumers.sort((a, b) => a[0].localeCompare(b[0]))) {
    // A bare directory prefix adds nothing when the same source names real
    // endpoints under it ("${BASE}" lines in the smoke script, for instance).
    const shown = paths.filter(
      (p) => !paths.some((other) => other !== p && other.startsWith(p + "/")),
    );
    const key = `${source}: ${shown.join(" ")}`;
    if (seen.has(key)) continue;
    seen.add(key);
    lines.push(`- **${source}** → ${shown.map((p) => `\`${p}\``).join(", ")}`);
  }

  const allowlisted = Object.keys(allowlist);
  if (allowlisted.length > 0) {
    lines.push(
      "",
      "## Known-unwired endpoints",
      "",
      "Exist in code, referenced nowhere yet — each carries a recorded reason:",
      "",
      "| Endpoint | Reason |",
      "| --- | --- |",
    );
    for (const path of allowlisted.sort()) {
      lines.push(`| \`${path}\` | ${allowlist[path]} |`);
    }
  }

  return lines.join("\n") + "\n";
}

export function buildSchemaDoc(tables) {
  const migrations = new Set(tables.map((t) => t.introducedIn));
  const lines = [
    HEADER,
    "",
    "# Database inventory",
    "",
    `${tables.length} tables across ${migrations.size} migrations, generated from`,
    "`supabase/migrations/`. The authoritative list lives here because this file",
    "is regenerated — hand-written counts go stale, this cannot.",
    "",
    "| Table | Introduced in |",
    "| --- | --- |",
  ];
  for (const { table, introducedIn } of tables) {
    lines.push(`| \`${table}\` | \`${introducedIn}\` |`);
  }
  return lines.join("\n") + "\n";
}
