/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCreativeRouteImport } from './routes/_authenticated/creative'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPublishRouteImport } from './routes/_authenticated/publish'
import { Route as AuthenticatedScenesRouteImport } from './routes/_authenticated/scenes'
import { Route as AuthenticatedTestsRouteImport } from './routes/_authenticated/tests'
import { Route as AuthenticatedPostsPostIdRouteImport } from './routes/_authenticated/posts.$postId'
import { Route as ApiPublicAutomationAnalyticsRouteImport } from './routes/api/public/automation/analytics'
import { Route as ApiPublicAutomationApprovedRouteImport } from './routes/api/public/automation/approved'
import { Route as ApiPublicAutomationBuildPlatesRouteImport } from './routes/api/public/automation/build-plates'
import { Route as ApiPublicAutomationCatalogSyncRouteImport } from './routes/api/public/automation/catalog-sync'
import { Route as ApiPublicAutomationGenerateTodayRouteImport } from './routes/api/public/automation/generate-today'
import { Route as ApiPublicAutomationPublishedRouteImport } from './routes/api/public/automation/published'
import { Route as ApiPublicAutomationRenderCampaignRouteImport } from './routes/api/public/automation/render-campaign'
import { Route as ApiPublicAutomationRenderSceneRouteImport } from './routes/api/public/automation/render-scene'
import { Route as ApiPublicCreativeClaimRouteImport } from './routes/api/public/creative/claim'
import { Route as ApiPublicCreativeCompleteRouteImport } from './routes/api/public/creative/complete'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreativeRoute = AuthenticatedCreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishRoute = AuthenticatedPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenesRoute = AuthenticatedScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsRoute = AuthenticatedTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsPostIdRoute =
  AuthenticatedPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAutomationAnalyticsRoute =
  ApiPublicAutomationAnalyticsRouteImport.update({
    id: '/api/public/automation/analytics',
    path: '/api/public/automation/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationApprovedRoute =
  ApiPublicAutomationApprovedRouteImport.update({
    id: '/api/public/automation/approved',
    path: '/api/public/automation/approved',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationBuildPlatesRoute =
  ApiPublicAutomationBuildPlatesRouteImport.update({
    id: '/api/public/automation/build-plates',
    path: '/api/public/automation/build-plates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationCatalogSyncRoute =
  ApiPublicAutomationCatalogSyncRouteImport.update({
    id: '/api/public/automation/catalog-sync',
    path: '/api/public/automation/catalog-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationGenerateTodayRoute =
  ApiPublicAutomationGenerateTodayRouteImport.update({
    id: '/api/public/automation/generate-today',
    path: '/api/public/automation/generate-today',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationPublishedRoute =
  ApiPublicAutomationPublishedRouteImport.update({
    id: '/api/public/automation/published',
    path: '/api/public/automation/published',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationRenderCampaignRoute =
  ApiPublicAutomationRenderCampaignRouteImport.update({
    id: '/api/public/automation/render-campaign',
    path: '/api/public/automation/render-campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationRenderSceneRoute =
  ApiPublicAutomationRenderSceneRouteImport.update({
    id: '/api/public/automation/render-scene',
    path: '/api/public/automation/render-scene',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreativeClaimRoute = ApiPublicCreativeClaimRouteImport.update({
  id: '/api/public/creative/claim',
  path: '/api/public/creative/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreativeCompleteRoute =
  ApiPublicCreativeCompleteRouteImport.update({
    id: '/api/public/creative/complete',
    path: '/api/public/creative/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/creative': typeof AuthenticatedCreativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/scenes': typeof AuthenticatedScenesRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/api/public/automation/analytics': typeof ApiPublicAutomationAnalyticsRoute
  '/api/public/automation/approved': typeof ApiPublicAutomationApprovedRoute
  '/api/public/automation/build-plates': typeof ApiPublicAutomationBuildPlatesRoute
  '/api/public/automation/catalog-sync': typeof ApiPublicAutomationCatalogSyncRoute
  '/api/public/automation/generate-today': typeof ApiPublicAutomationGenerateTodayRoute
  '/api/public/automation/published': typeof ApiPublicAutomationPublishedRoute
  '/api/public/automation/render-campaign': typeof ApiPublicAutomationRenderCampaignRoute
  '/api/public/automation/render-scene': typeof ApiPublicAutomationRenderSceneRoute
  '/api/public/creative/claim': typeof ApiPublicCreativeClaimRoute
  '/api/public/creative/complete': typeof ApiPublicCreativeCompleteRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/creative': typeof AuthenticatedCreativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/scenes': typeof AuthenticatedScenesRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/api/public/automation/analytics': typeof ApiPublicAutomationAnalyticsRoute
  '/api/public/automation/approved': typeof ApiPublicAutomationApprovedRoute
  '/api/public/automation/build-plates': typeof ApiPublicAutomationBuildPlatesRoute
  '/api/public/automation/catalog-sync': typeof ApiPublicAutomationCatalogSyncRoute
  '/api/public/automation/generate-today': typeof ApiPublicAutomationGenerateTodayRoute
  '/api/public/automation/published': typeof ApiPublicAutomationPublishedRoute
  '/api/public/automation/render-campaign': typeof ApiPublicAutomationRenderCampaignRoute
  '/api/public/automation/render-scene': typeof ApiPublicAutomationRenderSceneRoute
  '/api/public/creative/claim': typeof ApiPublicCreativeClaimRoute
  '/api/public/creative/complete': typeof ApiPublicCreativeCompleteRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/creative': typeof AuthenticatedCreativeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/publish': typeof AuthenticatedPublishRoute
  '/_authenticated/scenes': typeof AuthenticatedScenesRoute
  '/_authenticated/tests': typeof AuthenticatedTestsRoute
  '/_authenticated/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/api/public/automation/analytics': typeof ApiPublicAutomationAnalyticsRoute
  '/api/public/automation/approved': typeof ApiPublicAutomationApprovedRoute
  '/api/public/automation/build-plates': typeof ApiPublicAutomationBuildPlatesRoute
  '/api/public/automation/catalog-sync': typeof ApiPublicAutomationCatalogSyncRoute
  '/api/public/automation/generate-today': typeof ApiPublicAutomationGenerateTodayRoute
  '/api/public/automation/published': typeof ApiPublicAutomationPublishedRoute
  '/api/public/automation/render-campaign': typeof ApiPublicAutomationRenderCampaignRoute
  '/api/public/automation/render-scene': typeof ApiPublicAutomationRenderSceneRoute
  '/api/public/creative/claim': typeof ApiPublicCreativeClaimRoute
  '/api/public/creative/complete': typeof ApiPublicCreativeCompleteRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/calendar'
    | '/creative'
    | '/dashboard'
    | '/knowledge'
    | '/logs'
    | '/products'
    | '/publish'
    | '/scenes'
    | '/tests'
    | '/posts/$postId'
    | '/api/public/automation/analytics'
    | '/api/public/automation/approved'
    | '/api/public/automation/build-plates'
    | '/api/public/automation/catalog-sync'
    | '/api/public/automation/generate-today'
    | '/api/public/automation/published'
    | '/api/public/automation/render-campaign'
    | '/api/public/automation/render-scene'
    | '/api/public/creative/claim'
    | '/api/public/creative/complete'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/calendar'
    | '/creative'
    | '/dashboard'
    | '/knowledge'
    | '/logs'
    | '/products'
    | '/publish'
    | '/scenes'
    | '/tests'
    | '/posts/$postId'
    | '/api/public/automation/analytics'
    | '/api/public/automation/approved'
    | '/api/public/automation/build-plates'
    | '/api/public/automation/catalog-sync'
    | '/api/public/automation/generate-today'
    | '/api/public/automation/published'
    | '/api/public/automation/render-campaign'
    | '/api/public/automation/render-scene'
    | '/api/public/creative/claim'
    | '/api/public/creative/complete'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/creative'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge'
    | '/_authenticated/logs'
    | '/_authenticated/products'
    | '/_authenticated/publish'
    | '/_authenticated/scenes'
    | '/_authenticated/tests'
    | '/_authenticated/posts/$postId'
    | '/api/public/automation/analytics'
    | '/api/public/automation/approved'
    | '/api/public/automation/build-plates'
    | '/api/public/automation/catalog-sync'
    | '/api/public/automation/generate-today'
    | '/api/public/automation/published'
    | '/api/public/automation/render-campaign'
    | '/api/public/automation/render-scene'
    | '/api/public/creative/claim'
    | '/api/public/creative/complete'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAutomationAnalyticsRoute: typeof ApiPublicAutomationAnalyticsRoute
  ApiPublicAutomationApprovedRoute: typeof ApiPublicAutomationApprovedRoute
  ApiPublicAutomationBuildPlatesRoute: typeof ApiPublicAutomationBuildPlatesRoute
  ApiPublicAutomationCatalogSyncRoute: typeof ApiPublicAutomationCatalogSyncRoute
  ApiPublicAutomationGenerateTodayRoute: typeof ApiPublicAutomationGenerateTodayRoute
  ApiPublicAutomationPublishedRoute: typeof ApiPublicAutomationPublishedRoute
  ApiPublicAutomationRenderCampaignRoute: typeof ApiPublicAutomationRenderCampaignRoute
  ApiPublicAutomationRenderSceneRoute: typeof ApiPublicAutomationRenderSceneRoute
  ApiPublicCreativeClaimRoute: typeof ApiPublicCreativeClaimRoute
  ApiPublicCreativeCompleteRoute: typeof ApiPublicCreativeCompleteRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creative': {
      id: '/_authenticated/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof AuthenticatedCreativeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publish': {
      id: '/_authenticated/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof AuthenticatedPublishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenes': {
      id: '/_authenticated/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof AuthenticatedScenesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests': {
      id: '/_authenticated/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AuthenticatedTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/$postId': {
      id: '/_authenticated/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/automation/analytics': {
      id: '/api/public/automation/analytics'
      path: '/api/public/automation/analytics'
      fullPath: '/api/public/automation/analytics'
      preLoaderRoute: typeof ApiPublicAutomationAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/approved': {
      id: '/api/public/automation/approved'
      path: '/api/public/automation/approved'
      fullPath: '/api/public/automation/approved'
      preLoaderRoute: typeof ApiPublicAutomationApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/build-plates': {
      id: '/api/public/automation/build-plates'
      path: '/api/public/automation/build-plates'
      fullPath: '/api/public/automation/build-plates'
      preLoaderRoute: typeof ApiPublicAutomationBuildPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/catalog-sync': {
      id: '/api/public/automation/catalog-sync'
      path: '/api/public/automation/catalog-sync'
      fullPath: '/api/public/automation/catalog-sync'
      preLoaderRoute: typeof ApiPublicAutomationCatalogSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/generate-today': {
      id: '/api/public/automation/generate-today'
      path: '/api/public/automation/generate-today'
      fullPath: '/api/public/automation/generate-today'
      preLoaderRoute: typeof ApiPublicAutomationGenerateTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/published': {
      id: '/api/public/automation/published'
      path: '/api/public/automation/published'
      fullPath: '/api/public/automation/published'
      preLoaderRoute: typeof ApiPublicAutomationPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/render-campaign': {
      id: '/api/public/automation/render-campaign'
      path: '/api/public/automation/render-campaign'
      fullPath: '/api/public/automation/render-campaign'
      preLoaderRoute: typeof ApiPublicAutomationRenderCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/render-scene': {
      id: '/api/public/automation/render-scene'
      path: '/api/public/automation/render-scene'
      fullPath: '/api/public/automation/render-scene'
      preLoaderRoute: typeof ApiPublicAutomationRenderSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/creative/claim': {
      id: '/api/public/creative/claim'
      path: '/api/public/creative/claim'
      fullPath: '/api/public/creative/claim'
      preLoaderRoute: typeof ApiPublicCreativeClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/creative/complete': {
      id: '/api/public/creative/complete'
      path: '/api/public/creative/complete'
      fullPath: '/api/public/creative/complete'
      preLoaderRoute: typeof ApiPublicCreativeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCreativeRoute: typeof AuthenticatedCreativeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPublishRoute: typeof AuthenticatedPublishRoute
  AuthenticatedScenesRoute: typeof AuthenticatedScenesRoute
  AuthenticatedTestsRoute: typeof AuthenticatedTestsRoute
  AuthenticatedPostsPostIdRoute: typeof AuthenticatedPostsPostIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCreativeRoute: AuthenticatedCreativeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPublishRoute: AuthenticatedPublishRoute,
  AuthenticatedScenesRoute: AuthenticatedScenesRoute,
  AuthenticatedTestsRoute: AuthenticatedTestsRoute,
  AuthenticatedPostsPostIdRoute: AuthenticatedPostsPostIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAutomationAnalyticsRoute: ApiPublicAutomationAnalyticsRoute,
  ApiPublicAutomationApprovedRoute: ApiPublicAutomationApprovedRoute,
  ApiPublicAutomationBuildPlatesRoute: ApiPublicAutomationBuildPlatesRoute,
  ApiPublicAutomationCatalogSyncRoute: ApiPublicAutomationCatalogSyncRoute,
  ApiPublicAutomationGenerateTodayRoute: ApiPublicAutomationGenerateTodayRoute,
  ApiPublicAutomationPublishedRoute: ApiPublicAutomationPublishedRoute,
  ApiPublicAutomationRenderCampaignRoute:
    ApiPublicAutomationRenderCampaignRoute,
  ApiPublicAutomationRenderSceneRoute: ApiPublicAutomationRenderSceneRoute,
  ApiPublicCreativeClaimRoute: ApiPublicCreativeClaimRoute,
  ApiPublicCreativeCompleteRoute: ApiPublicCreativeCompleteRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
